# ----
# Site

title: "Wenhan's Home"
url: "https://ivyee17.github.io"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:


# self-intro page
name: "Wu Wenhan"
position: "Student @ ECNU"
slogen: "
Life is not a check-list of acquisition or achievement. Your qualifications, your CV, are not your life. Life is difficult, and complicated, and beyond anyone’s total control, and the humility to know that will enable you to survive its vicissitudes."

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo:  "/images/essay-page/profile.png"   # must have! Do like this: /images/siteicon.png
description:

# Site Author
author:
  name             : "Wu Wenhan"
  avatar           : "/essay-page/profile.png"
  bio              : "Student"
  location         : "East China Normal <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;University"
  employer         :
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=NBSeJLkAAAAJ&hl=en&oi=sra"
  email            :  "1020645987@qq.com"
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "ivyee17"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : #"https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : "https://www.linkedin.cn/injobs/in/wu-wenhan-52453a206"
  orcid            : "http://orcid.org/yourorcidurl"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : # "replacethistwitterhandle"
  vine             :
  weibo            : "weibo.com"
  xing             :
  youtube          : "youtube.com"
  wikipedia        :


social:
  name: Hydra Template
  links:
    - https://github.com/CloudCannon/hydra-jekyll-template

# -----
# Build

Timezone: Etc/UTC

collections:
  publications:
    output: true
    permalink: /:collection/:path/
  essays:
    output: true
    permalink: /:collection/:title/
  musics:
    output: true
    permalink: /:collection/:path/
  resumes:
    output: true
    permalink: /resumes/:categories/:title/
  
paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: publications
    values:
      layout: essay-page/single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: essays
    values:
      layout: essay-page/single-essay
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: musics
    values:
      layout: music-page
  - scope:
      path: ""
      type: resumes
    values:
      layout: resume-page/template2


jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS

_comments:
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  pricing_table: Update the information in the pricing tables.
  highlight: Emphasis the text
  color: The background colour used in the plan name and call to action.
  new_window: Open link in new window

#theme: jekyll-theme-leap-day

sass:
  sass_dir: _sass
  style: compressed